---
- name: Save configuration
  hosts: "{{ host }}"
  gather_facts: no

  vars:
    host: "{{ inventory_hostname }}"
    ansible_connection: network_cli

  tasks:
    - name: save running to startup when modified
      exos_config:
        save_when: modified
