version: 2
jobs:
  build:
    docker:
      - image: williamyeh/ansible:ubuntu16.04
    steps:
      - checkout
      - run:
          name: Install ansible-lint
          command: |
            pip install ansible-lint
            ansible-lint --version
            ansible --version
      - run:
          name: Ansible YAML syntax check
          command: |
            cd slxos/playbooks
            ansible-playbook --syntax-check *.yaml */*.yml
      - run:
          name: Ansible-lint check
          command: |
            cd slxos/playbooks
            ansible-lint -v *.yaml */*.yml
